### PR TITLE
Use `once_cell` instead of `lazy_static`

### PR DESCRIPTION
**Pull request by VirxEC**
The `once_cell` crate looks like it will become the standard very soon, as part of its code has already been merged into Rust's std. This PR moves to use the crate's `Lazy` type instead of the `lazy_static` macro.

The end-user shouldn't notice any changes, but if the `Lazy` type does get merged into the std then that's one less dependency needed (unless you're working with no std)

It also removes all the `#![cfg_attr(not(feature = "stable"), feature(proc_macro_hygiene))]` from the tests.

Feel free to ignore this PR if you still like `lazy_static`

### CODE REVIEW

**Comment by SOF3** [comment]
Since it is getting into the standard library, why not wait till the std one is stable and use that directly?

**Comment by VirxEC** [comment]
As per <https://github.com/rust-lang/rust/issues/109736> the `Lazy` type (which appears to have been renamed to `LazyLock` is only available in nightly Rust atm and has no ETA for being stable. Only the base types like `once_cell` have been stabilized.

**Comment by SOF3** [comment]
Could you merge/rebase master to fix the CI?

**Comment by VirxEC** [comment]
Done

**Review by SOF3 — APPROVED** [review]
thanks!

**Pull request merged**
