### PR TITLE
Auto rebuild workaround

### LINKED ISSUE #12: [BUG] Modifying the file included with `flate!` doesn't automatically trigger rebuild
## To reproduce:

1. Paste this code into `main.rs`:
```rust
fn main() {
    include_flate::flate!(static FOO_STR: str from "foo.bar");
    println!("{}", FOO_STR.as_str());
}
```
2. Create a `foo.bar` under crate root, and write some content
3. Run `cargo run`, and observe that the content of `foo.bar` is correctly printed
4. Modify the contents of `foo.bar` and save
5. Run `cargo run` again, and observe that a rebuild is not triggered, and the old contents of `foo.bar` are printed
6. Replace `flate!` with `include_str!`, repeat steps 2-5, and observe that a rebuild is triggered

---

I am reporting this as a bug primarily because `include-flate` is advertised as a drop-in replacement for `include_str`, so this difference in behaviour could be confusing.

Also I agree with the standard library that automatically triggering a rebuild is the sensible default, so `include-flate` should try to replicate this behaviour. That being said, I'm not too familiar with the implementation details of `include_str!`, so perhaps it's driven by compiler magic and the automatic rebuild behaviour is not replicable in third-party crates, I'm not sure.

### PR DESCRIPTION
**Pull request by cyqsimon**
Closes #12.

I didn't know how to write a test for this. It's not ideal, but thinking of how I can test this hurts my brain. Sorry ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by SOF3** [comment]
Are you sure it doesn't include the raw contents into the bin output?

**Comment by cyqsimon** [comment]
> Are you sure it doesn't include the raw contents into the bin output?

Yeah I checked. See https://github.com/SOF3/include-flate/issues/12#issuecomment-1427037681

**Comment by cyqsimon** [comment]
With both the default `debug` and `release` profiles, the raw contents are optimised away by the compiler.

Maybe there's some optimisation setting somewhere that the user can set that will prevent this behaviour, but those situations are probably too niche to warrant special consideration TBH.

**Review by SOF3 — APPROVED** [review]

**Comment by SOF3** [comment]
I am a bit concerned about the impacts, so I will release this in a new minor.

**Pull request merged**
